### PR TITLE
CORE-1716: move schema migrations to golang-migrate.

### PR DESCRIPTION
**Pull request by slr71**
The migrations are still going to be run from within `QMS` itself, but we'll now use [golang-migrate][1] to do the migrations for us. This give us a little bit more flexibility because it allows us to define triggers and automatically update constraints on existing columns if we need to.

[1]: https://github.com/golang-migrate/migrate

### CODE REVIEW

**Comment by slr71** [comment]
I just realized that I forgot to update the Dockerfile to include the migrations. 😖 I'll mark this PR as a draft for now.

**Comment by slr71** [comment]
The Dockerfile has been updated. I also switched the base image from `busybox` to `debian:stable-slim`, which can make troubleshooting easier sometimes.

**Review by johnworth — APPROVED** [review]
:shipit:

**Comment by slr71** [comment]
Thanks for the review!

**Pull request merged**
